require("./testSwagger");
require("./testCode");
require("./testLegalLimits");
require("./testJurisdiction");
require("./testCompany");
require("./testProduct");
require("./testTap");
require("./testPumpingstation");
require("./testObservation");
