language: node_js
services: mongodb
node_js:
- '6'
env:
  secure: qLB2jqXqNLWOy/pjqCmxjZL3wYVfpdfpm4dgF2/c99kAnIo/b7sz+7mZzBrmddC99Tq+jH0YeCUhlXjGtqQnOUPLCpcmRpY5xBaOV1Gtm6gJVtD8GpcLiVHfk3lSTDzwgzVQpCgG/7wsES6F88PL8t4i6m/3Ww3Xt7DMeurZw8Tx+WizuvZF65Gs4mk3IdI6ZpdAWvGKw6ukeSHs6Vb/Q04MxG3qdFCR+LFQqlEL0Y73nOxUGmjWpdIp6p9+eaFKO0CfGzqF8Awv6tjBsSMz5DTytkUWCRcSoYlfeykPd6j3mTNIKaa/Cr/1pNBG7BzJgb0GVGadjJ76Ke3N5np/Uavo9U8f5dVOCrcdF1jgKRNIkFg5qNSbSdKPFiWB3IQnYsUR1HW7J0gI5bpCY0ktkQIBnJ7AvudUyHRlK3n1uvjo+l3AcE6rqkHEEVASsXuH/euNOo7f038qKRtzKDeu4cdcxnY4B+0JwlqevwE6tVKupWxbqv1Qw+SXBLl5TLMiMkESfn59v66gIsRQ1b/FnEQN+Xa4HEbSo8Y7WzWamQ0un+cV1utbecW+TjSp3Csqhna3qTctBm8787iFXT1qZa9+bZYdLk9EqCT4elBVlt91rDIsz4MTBV5uAUsS2A8UHvQhIVugKd0rcaIFw5kmEYQ//MntFGRKyMuxsT9uW0E=
